### ISSUE TITLE
导入失败

### ISSUE THREAD

**Issue by 2570961835** [BigYoungs/ARL-Finger-ADD-Pro#1]
报错以下问题：
-Finger-ADD-Pro-V1.0.1-BigYouong\arl-finger-add-pro/all_fingers/tmp_arl_finger.yml，上传失败！失败原因：{"message
": "\u7cfb\u7edf\u5f02\u5e38 msg:Expecting value: line 1 column 1 (char 0)", "code": 500, "data": {"msg": "Expecting value: line 1 column 1 (char 0)"}}

**Comment by BigYoungs** [comment]
> 报错以下问题： -Finger-ADD-Pro-V1.0.1-BigYouong\arl-finger-add-pro/all_fingers/tmp_arl_finger.yml，上传失败！失败原因：{"message ": "\u7cfb\u7edf\u5f02\u5e38 msg:Expecting value: line 1 column 1 (char 0)", "code": 500, "data": {"msg": "Expecting value: line 1 column 1 (char 0)"}}

核对ARL的版本是否与此工具匹配，应该是版本不匹配导致。
